apiVersion: v1
kind: Service
metadata:
  name: ace-lora-training-studio
  labels:
    app: ace-lora-training-studio
spec:
  selector:
    app: ace-lora-training-studio
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
